EXP_BASE_DIR=$1
INIT_EXP_DATE=$2
EXP_DATE_PREFIX=$3
NC_ID=$4
PROJECT_NAME=$5
EXPERIENCE_LIST_PATH="$ACCELOPT_BASE_DIR/prompts/empty_rewrites.json"
REL_TOL=$6
ORG_NAME=$7
ITERS=$8
BREADTH=$9
TOPK_CANDIDATES=$10
NUM_SAMPLES=$11
MAX_THRESHOLD=$12
MIN_THRESHOLD=$13
TOPK=$14
EXP_N=$15


LAST_EXP_DATE=$INIT_EXP_DATE
for i in $(seq 1 $ITERS); do
    # Get the current exp date from time using Pacific time
    CURRENT_EXP_DATE="$EXP_DATE_PREFIX-$(TZ='America/Los_Angeles' date +%m-%d-%H-%M)"
    echo "$CURRENT_EXP_DATE" >> "$EXP_BASE_DIR/log.txt"
    EXPERIENCE_LIST_PATH="$EXP_BASE_DIR/$LAST_EXP_DATE/rewrites/aggregated_rewrites_list.json"
    mkdir -p $EXP_BASE_DIR/$CURRENT_EXP_DATE
    $ACCELOPT_BASE_DIR/templates/complete_local/run_init.sh $CURRENT_EXP_DATE $LAST_EXP_DATE $EXP_BASE_DIR $PROJECT_NAME $ORG_NAME
    $ACCELOPT_BASE_DIR/templates/complete_local/run_accum_rewrites.sh $CURRENT_EXP_DATE $EXP_BASE_DIR $NC_ID $MAX_THRESHOLD $MIN_THRESHOLD $TOPK $TOPK_CANDIDATES $PROJECT_NAME $REL_TOL $ORG_NAME
    $ACCELOPT_BASE_DIR/templates/complete_local/run_body.sh $CURRENT_EXP_DATE $EXP_BASE_DIR $EXPERIENCE_LIST_PATH $NC_ID $BREADTH $NUM_SAMPLES $EXP_N $PROJECT_NAME $REL_TOL $ORG_NAME
    LAST_EXP_DATE=$CURRENT_EXP_DATE
done
